-- ONE MILLION VARIABLES GO BRRR
-- ckGalaxy as in c00lkidd galaxy wow so funny i know
local ckGalaxy = {}

local ServerScriptService = game:GetService("ServerScriptService")

ckGalaxy.ServerEventsModule = require(ServerScriptService.Server.ServerEventsModule)

-- Cave Room
ckGalaxy.GrandDoor = workspace.Cave.Inside.ButtonDoor :: Model
ckGalaxy.HintLabel = workspace.Cave.Inside.CodeObjects.LockImage.SurfaceGui.HintText

return ckGalaxy
