-- UNUSED
--[[		chance for random useless stuff to happen
	map turns into a different season
	bunch of cars
	different sun decal
	dummy npc (to be changed)
	escape ending 0.X% chance to see the Spectre talk
		- you can't escape me. this is not the way. 
		- i see you are curious.
	sleep ending variances
		chance for cutscene upon sleep?]]

-- task.wait()

-- local funValue = math.random(100)
-- local randomValue = math.random(100)

-- -- FUN

-- local function changeSun() end

-- local function spawnNPC() end

-- local function modifyEscapeEnding() end

-- local function modifySleepEnding() end

-- -- RANDOM

-- local function changeSeason() end

-- local function spawnCars() end
